server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
---
spring:
  profiles: ribbon-only
  jpa:
    show-sql: true

server:
  port: ${PORT:8080}

disciplina-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081,localhost:18081,localhost:28081