server:
  port: ${PORT:8081}

spring:
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
feign:
  hystrix:
    enabled: true    